template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: jfrog_pipeline
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}

pipelines:
  - name: demo_maven
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "8"
          deployerSnapshotRepo: {{ .Values.deployerRepo }}
          deployerReleaseRepo: {{ .Values.deployerRepo }}
          inputResources:
            - name: jfrog_pipeline
          integrations:
            - name: {{ .Values.artifactory }}

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info
