template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: jfrog_pipeline
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}

pipelines:
  - name: pipelines_caching
    steps:
      - name: pipelines_caching
        type: Bash
        configuration:
          inputResources:
            - name: jfrog_pipeline
        execution:
          onExecute:
            - restore_cache_files maven_cache ~/.m2
            - npm install
          onComplete:
            - add_cache_files ~/.m2 maven_cache
  - name: demo_maven
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "8"
          deployerSnapshotRepo: {{ .Values.deployerRepo }}
          deployerReleaseRepo: {{ .Values.deployerRepo }}
          inputResources:
            - name: jfrog_pipeline
          integrations:
            - name: {{ .Values.artifactory }}

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info
      - name: docker_build
        steps:
          - name: bld_image
            type: DockerBuild
            configuration:
              dockerFileLocation: .
              dockerFileName: Dockerfile
              dockerImageName: demo.jfrogchina.com/demo-docker-prod-local/multi    # replace with your fully qualified Docker registry/image name
              dockerImageTag: ${run_number}
              inputResources:
                - name: mvn_build_step
              integrations:
                - name: {{ .Values.artifactory }}
